apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: database
  labels:
    app: cassandra
spec:
  type: NodePort
  ports:
    - name: native
      protocol: TCP
      port: 9042
      targetPort: 9042
      nodePort: 30042
    - name: jmx
      protocol: TCP
      port: 7199
      targetPort: 7199
      nodePort: 30043
  selector:
    app: cassandra
  externalTrafficPolicy: Local